Removing these lines because they fail with the following error message:
```
+ kubectl logs -c apiserver -l app=navigator,component=apiserver
error: a container cannot be specified when using a selector (-l)
```